apiVersion: v1
global:
  image:
    repository: btcpayserver/btcpayserver
    tag: "1.13.0"
  namespace: btcpay
  bitcoinNetwork: regtest

bitcoind:
  enabled: true
  replicaCount: 1
  image:
    repository: lightninglabs/bitcoin-core
    tag: "27"
  service:
    type: ClusterIP
    port: 18443
  persistence:
    enabled: true
    size: 10Gi

db:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 5Gi

lnd:
  enabled: true
  replicaCount: 1
  image:
    repository: lightninglabs/lnd
    tag: "0.18.0-beta"
  service:
    type: ClusterIP
    ports:
      grpc: 10009
      rest: 8080
      p2p: 9735
  persistence:
    enabled: true
    size: 5Gi

nbxplorer:
  enabled: true
  replicaCount: 1
  image:
    repository: nicolasdorier/nbxplorer
    tag: "2.5.27"
  service:
    type: ClusterIP
    port: 32838

btcpayserver:
  enabled: true
  replicaCount: 1
  image:
    repository: btcpayserver/btcpayserver
    tag: "1.13.0"
  initContainerImage: busybox
  service:
    type: ClusterIP
    port: 23002
  lndDataPvc: lnd-data-pvc
  networkConfigMap: btcpay-network-config
  rpcSecrets: rpc-secrets
  postgres: "Host=db;Port=5432;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Database=btcpay"
  btcrpcurl: "http://$(RPC_USER):$(RPC_PASSWORD)@bitcoind:18443/"
  btcexplorerurl: "http://nbxplorer:32838/"
  btcnbxplorerurl: "http://nbxplorer:32838/"
  btcexternalurl: "http://localhost:23000/"
  lndrpcurl: "https://lnd:8080/"
  lndgrpcurl: "lnd:10009"
  lndmacaroondir: "/lnd"
  lndcertdir: "/lnd"
  aspnetcoreUrls: "http://0.0.0.0:23002"
  regtestBtcLightning: "type=lnd-rest;server=https://lnd:8080/;macaroonfilepath=/lnd/admin.macaroon;certthumbprint=7f3f8dc0b35dc5b51752897e0e6bee4f624fb9ba74bbb4f8519e3914eb4d14c7"
  logs: "Debug"

rtl:
  enabled: true
  replicaCount: 1
  image:
    repository: shahanafarooqui/rtl
    tag: "0.15.1"
  service:
    type: ClusterIP
    port: 3000

ingress:
  enabled: true
  hosts:
    - host: btcpay.local
      paths:
        - /
    - host: rtl.local
      paths:
        - /

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
