apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lnd
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
        - name: lnd
          image: {{ .Values.lnd.image }}
          command:
            - sh
            - -c
            - |
              exec lnd \
                --bitcoin.active \
                --bitcoin.{{ .Values.bitcoin.network }} \
                --bitcoin.node=bitcoind \
                --bitcoind.rpchost=bitcoind:18443 \
                --bitcoind.rpcuser=$RPC_USER \
                --bitcoind.rpcpass=$RPC_PASSWORD \
                --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 \
                --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 \
                --rpclisten=0.0.0.0:10009 \
                --restlisten=0.0.0.0:8080 \
                --listen=0.0.0.0:9735 \
                --wallet-unlock-password-file=/run/secrets/lnd-wallet-password
          envFrom:
            - configMapRef:
                name: btcpay-network-config
            - secretRef:
                name: rpc-secrets
          ports:
            - containerPort: 9735 # Lightning P2P
            - containerPort: 10009 # gRPC
            - containerPort: 8080 # REST
          volumeMounts:
            - name: lnd-data
              mountPath: /root/.lnd
            - name: lnd-wallet-password
              mountPath: /run/secrets/lnd-wallet-password
              subPath: LND_WALLET_PASSWORD
      volumes:
        - name: lnd-data
          persistentVolumeClaim:
            claimName: lnd-data-pvc
        - name: lnd-wallet-password
          secret:
            secretName: rpc-secrets