apiVersion: apps/v1
kind: Deployment
metadata:
  name: btcpayserver
  namespace: { { .Release.Namespace } }
  labels:
    app: btcpayserver
spec:
  replicas: { { .Values.btcpayserver.replicaCount | default 1 } }
  selector:
    matchLabels:
      app: btcpayserver
  template:
    metadata:
      labels:
        app: btcpayserver
    spec:
      initContainers:
        - name: copy-lnd-creds
          image:
            { { .Values.btcpayserver.initContainerImage | default "busybox" } }
          command:
            - sh
            - -c
            - |
              while [ ! -f /lnd/data/chain/bitcoin/${BTCPAY_NETWORK:-testnet}/admin.macaroon ]; do
                echo "Waiting for LND macaroon..."
                sleep 2
              done
              cp /lnd/data/chain/bitcoin/${BTCPAY_NETWORK:-testnet}/admin.macaroon /lnd/admin.macaroon
          env:
            - name: BTCPAY_NETWORK
              valueFrom:
                configMapKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.networkConfigMap | default "btcpay-network-config",
                      },
                    }
                  key: BITCOIN_NETWORK
          volumeMounts:
            - name: lnd-data
              mountPath: /lnd
      containers:
        - name: btcpayserver
          image:
            {
              {
                .Values.btcpayserver.image | default "btcpayserver/btcpayserver:1.13.0",
              },
            }
          env:
            - name: BTCPAY_NETWORK
              valueFrom:
                configMapKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.networkConfigMap | default "btcpay-network-config",
                      },
                    }
                  key: BITCOIN_NETWORK

            - name: RPC_USER
              valueFrom:
                secretKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.rpcSecrets | default "rpc-secrets",
                      },
                    }
                  key: RPC_USER
            - name: RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.rpcSecrets | default "rpc-secrets",
                      },
                    }
                  key: RPC_PASSWORD

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.rpcSecrets | default "rpc-secrets",
                      },
                    }
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:
                    {
                      {
                        .Values.btcpayserver.rpcSecrets | default "rpc-secrets",
                      },
                    }
                  key: POSTGRES_PASSWORD

            - name: BTCPAY_POSTGRES
              value:
                {
                  {
                    .Values.btcpayserver.postgres | default "Host=postgres;Port=5432;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Database=btcpay" | quote,
                  },
                }
            - name: BTCPAY_BTCRPCURL
              value:
                {
                  {
                    .Values.btcpayserver.btcrpcurl | default "http://raptcuser:securepass@bitcoind:18443/" | quote,
                  },
                }
            - name: BTCPAY_BTCEXPLORERURL
              value:
                {
                  {
                    .Values.btcpayserver.btcexplorerurl | default "http://raptcuser:securepass@nbxplorer:32838/" | quote,
                  },
                }
            - name: BTCPAY_BTCNBXPLORERURL
              value:
                {
                  {
                    .Values.btcpayserver.btcnbxplorerurl | default "http://raptcuser:securepass@nbxplorer:32838/" | quote,
                  },
                }
            - name: BTCPAY_BTCEXTERNALURL
              value:
                {
                  {
                    .Values.btcpayserver.btcexternalurl | default "http://localhost:23000/" | quote,
                  },
                }
            - name: BTCPAY_LNDRPCURL
              value:
                {
                  {
                    .Values.btcpayserver.lndrpcurl | default "https://lnd:8080/" | quote,
                  },
                }
            - name: BTCPAY_LNDGRPCURL
              value:
                {
                  {
                    .Values.btcpayserver.lndgrpcurl | default "lnd:10009" | quote,
                  },
                }
            - name: BTCPAY_LNDMACAROONDIR
              value:
                {
                  {
                    .Values.btcpayserver.lndmacaroondir | default "/lnd" | quote,
                  },
                }
            - name: BTCPAY_LNDCERTDIR
              value:
                { { .Values.btcpayserver.lndcertdir | default "/lnd" | quote } }
            - name: ASPNETCORE_URLS
              value:
                {
                  {
                    .Values.btcpayserver.aspnetcoreUrls | default "http://0.0.0.0:23002" | quote,
                  },
                }
            - name: BTCPAY_REGTEST_BTC_LIGHTNING
              value:
                {
                  {
                    .Values.btcpayserver.regtestBtcLightning | default "type=lnd-rest;server=https://lnd:8080/;macaroonfilepath=/lnd/admin.macaroon;certthumbprint=7f3f8dc0b35dc5b51752897e0e6bee4f624fb9ba74bbb4f8519e3914eb4d14c7" | quote,
                  },
                }
            - name: BTCPAY_LOGS
              value: { { .Values.btcpayserver.logs | default "Debug" | quote } }
          ports:
            - containerPort: 23002
          volumeMounts:
            - name: lnd-data
              mountPath: /lnd
              readOnly: false
      volumes:
        - name: lnd-data
          persistentVolumeClaim:
            claimName:
              { { .Values.btcpayserver.lndDataPvc | default "lnd-data-pvc" } }
