apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: btcpayserver-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.btcpay.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: btcpayserver
                port:
                  number: {{ .Values.btcpay.servicePort }}