apiVersion: v1
kind: Service
metadata:
  name: btcpayserver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: btcpayserver
  ports:
    - name: http
      port: 23002
      targetPort: 23002
  type: ClusterIP