apiVersion: v1
kind: Service
metadata:
  name: lnd
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: lnd
  ports:
    - name: p2p
      port: 9735
      targetPort: 9735
    - name: grpc
      port: 10009
      targetPort: 10009
    - name: rest
      port: 8080
      targetPort: 8080
  type: ClusterIP