apiVersion: v1
kind: Service
metadata:
  name: nbxplorer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nbxplorer
  ports:
    - name: http
      port: 32838
      targetPort: 32838
  type: ClusterIP