apiVersion: v1
kind: Service
metadata:
  name: bitcoind-nodeport
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: bitcoind
  ports:
    - name: rpc
      port: 18443
      targetPort: 18443
      nodePort: {{ .Values.bitcoind.nodePort.rpc }}
    - name: p2p
      port: 18444
      targetPort: 18444
      nodePort: {{ .Values.bitcoind.nodePort.p2p }}
    - name: zmqblock
      port: 28332
      targetPort: 28332
      nodePort: {{ .Values.bitcoind.nodePort.zmqblock }}
    - name: zmqtx
      port: 28333
      targetPort: 28333
      nodePort: {{ .Values.bitcoind.nodePort.zmqtx }}