apiVersion: v1
kind: Service
metadata:
  name: rtl
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rtl
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  type: ClusterIP