apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-grafana-lb
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
spec:
  type: LoadBalancer
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
