apiVersion: v1
kind: Service
metadata:
  name: bitcoind-nodeport
  namespace: btcpay
spec:
  type: NodePort
  selector:
    app: bitcoind
  ports:
    - name: rpc
      port: 18443
      targetPort: 18443
      nodePort: 31843
