apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: btcpay
spec:
  selector:
    app: bitcoind
  ports:
    - name: rpc
      port: 8332
      targetPort: 8332
    - name: p2p
      port: 8333
      targetPort: 8333
    - name: zmqblock
      port: 28332
      targetPort: 28332
    - name: zmqtx
      port: 28333
      targetPort: 28333
  type: ClusterIP
