apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: btcpay
spec:
  selector:
    app: bitcoind
  ports:
    - name: rpc
      port: 18443
      targetPort: 18443
    - name: p2p
      port: 18444
      targetPort: 18444
    - name: zmqblock
      port: 28332
      targetPort: 28332
    - name: zmqtx
      port: 28333
      targetPort: 28333
  type: ClusterIP
