apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
  namespace: btcpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
        - name: bitcoind
          image: lightninglabs/bitcoin-core:27
          command:
            - sh
            - -c
            - |
              if [ ! -d "/bitcoin/.bitcoin/regtest/wallets/regtestwallet" ]; then
                echo "Creating wallet..."
                bitcoind \
                  -datadir=/bitcoin/.bitcoin \
                  -regtest=1 \
                  -daemon \
                  -rpcallowip=0.0.0.0/0 \
                  -rpcbind=0.0.0.0 \
                  -rpcuser=$RPC_USER \
                  -rpcpassword=$RPC_PASSWORD \
                  -disablewallet=0
                sleep 3
                bitcoin-cli -regtest -rpcuser=$RPC_USER -rpcpassword=$RPC_PASSWORD createwallet regtestwallet
                bitcoin-cli -regtest -rpcuser=$RPC_USER -rpcpassword=$RPC_PASSWORD stop
                sleep 3
              fi

              exec bitcoind \
                -datadir=/bitcoin/.bitcoin \
                -printtoconsole \
                -regtest=1 \
                -port=18444 \
                -rpcport=18443 \
                -rpcallowip=0.0.0.0/0 \
                -rpcbind=0.0.0.0 \
                -zmqpubrawblock=tcp://0.0.0.0:28332 \
                -zmqpubrawtx=tcp://0.0.0.0:28333 \
                -rpcuser=$RPC_USER \
                -rpcpassword=$RPC_PASSWORD \
                -listen=1 \
                -whitelist=0.0.0.0/0 \
                -disablewallet=0 \
                -wallet=regtestwallet
          envFrom:
            - configMapRef:
                name: btcpay-network-config
            - secretRef:
                name: rpc-secrets
          ports:
            - containerPort: 18443 # RPC (regtest)
            - containerPort: 18444 # P2P (regtest)
            - containerPort: 28332 # ZMQ block
            - containerPort: 28333 # ZMQ tx
          volumeMounts:
            - name: bitcoind-data
              mountPath: /bitcoin/.bitcoin
      volumes:
        - name: bitcoind-data
          persistentVolumeClaim:
            claimName: bitcoind-data-pvc
