apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnd
  namespace: btcpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lnd
  template:
    metadata:
      labels:
        app: lnd
    spec:
      containers:
        - name: lnd
          image: lightninglabs/lnd:v0.18.0-beta
          args:
            - "--bitcoin.active"
            - "--bitcoin.${BITCOIN_NETWORK}"
            - "--bitcoin.node=bitcoind"
            - "--bitcoind.rpchost=bitcoind:8332"
            - "--bitcoind.rpcuser=$(RPC_USER)"
            - "--bitcoind.rpcpass=$(RPC_PASSWORD)"
            - "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
            - "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
            - "--rpclisten=0.0.0.0:10009"
            - "--restlisten=0.0.0.0:8080"
            - "--listen=0.0.0.0:9735"
          envFrom:
            - configMapRef:
                name: btcpay-network-config
            - secretRef:
                name: rpc-secrets
          ports:
            - containerPort: 9735 # Lightning P2P
            - containerPort: 10009 # gRPC
            - containerPort: 8080 # REST
          volumeMounts:
            - name: lnd-data
              mountPath: /root/.lnd
      volumes:
        - name: lnd-data
          persistentVolumeClaim:
            claimName: lnd-data-pvc
